### PR TITLE
feat: typescript, smoke-tests, min-stock option

### PR DESCRIPTION
**Pull request by Ephigenia**
Full typescript rewrite for better type-generation and future development.

- adds min-stock option to stock command
- adds smoke tests for several countries
- adds postman collection & schema
- adds workflow that runs postman collection on all countries for smoke tests
- adds more tests

BREAKING CHANGE:: some attributes and behavior may have changed as the whole lib has been re-written in TypeScript. Please update your integrations carefully.

### CODE REVIEW

**Comment by Teko012** [comment]
@Ephigenia `2.0.0-alpha.7` was released, but the package is missing the code from it.

**Comment by Ephigenia** [comment]
I completely messed up the version tags and published versions. I hopefully have fixed in soon and the alpha package will have contents again.

**Comment by Teko012** [comment]
Thanks for looking into it!

Something might be still missing, I'm getting this:
`npx ikea-availability-checker@2.0.0-alpha.8 stock
sh: ikea-availability: command not found
npx ikea-availability-checker@2.0.0-alpha.6 stock
please provide country code and/or store id`

**Comment by Teko012** [comment]
It works now, we have a new error:
```
/node_modules/.bin/ikea-availability: line 1: use strict: command not found
/node_modules/.bin/ikea-availability: line 2: syntax error near unexpected token `exports,'
/node_modules/.bin/ikea-availability: line 2: `Object.defineProperty(exports, "__esModule", { value: true });'
```
I think we are missing `#!/usr/bin/env node` from the `dist/src/cli/index.js`

**Comment by Ephigenia** [comment]
@Teko012 published a new version which includes the shebang for node again. Works now. I’ve played around with it a bit and seems to be working well. My plan would be to test it out a bit and if it works publish a 2.0 release and later add the abilities to get stores and countries later.

**Comment by Ephigenia** [comment]
@Teko012 Do you have any additional thoughts before publishing a 2.0 version?

**Comment by Teko012** [comment]
@Ephigenia Does it just silently fails/skips now if a store is unknown to it? For example, `cn` has way more stores then it shows/tests for. My expectation would be to either fail (at least in the test, if we want to test for every store if it's in the dataset), or just show the store with some generic text, but still show it in the results.

**Comment by Teko012** [comment]
I would also fix the regression I mentioned:

> There is also a regression between `.6` and `.9` at `restockDate`: before it said `in 2d (2023-01-13)`, now it's just `in 2`

**Comment by Ephigenia** [comment]
> @Ephigenia Does it just silently fails/skips now if a store is unknown to it? For example, `cn` has way more stores then it shows/tests for. My expectation would be to either fail (at least in the test, if we want to test for every store if it's in the dataset), or just show the store with some generic text, but still show it in the results.

Right now the availability takes only these stores into account that are listed in the static stores list. That could mean that some stores are missing. I’m planning to update this list using a script that's requesting the list of stores that you proposed.

CI smokey tests would only fail if one of the known stores returns a invalid result.

**Comment by Teko012** [comment]
I checked the new version it's `in 5 (2023-01-23)` instead of `in 5d (2023-01-23)`. Can we add back the `d` as well?

**Comment by Ephigenia** [comment]
@Teko012 thanks for your patience and checking it again. I’ve added a test for the report now so that won't happen again - hopefully :D

**Comment by Teko012** [comment]
Sounds good! The v1 version had a forecast column as well, is that something thats not available on the new API?

**Comment by Ephigenia** [comment]
@Teko012 the "availabilities" endpoint doesn’t seem to support a forecast column. Only some items and stores seem to support the restock information.

**Pull request merged**
