### PR TITLE
fix(iows): propagate timeout errors

### PR DESCRIPTION
**Pull request by gitolicious**
Some of my requests got me _ECONNABORTED timeout of 5000ms exceeded_ errors, though the error was not propagated. It gave _Cannot read properties of undefined (reading 'headers')_ errors.
With these changes, the error is properly shown.

### CODE REVIEW

**Comment by gitolicious** [comment]
@Ephigenia, it looks like the automated pipeline checks are not working properly. Test results are actually OK.

**Comment by Ephigenia** [comment]
@gitolicious I will try to look tomorrow

**Comment by Ephigenia** [comment]
Somehow the build tasks which require a valid GITHUB_TOKEN to post a comment are not working. I’ll check that later.

I added some code to the cli-stock so that timeout errors are listed as "TIMEOUT" in the table instead of throwing the error.

**Comment by gitolicious** [comment]
That sounds reasonable, thx!

**Pull request merged**
