### PR TITLE
fix(stores): add fi, gb, ee, lv stores and remove closed gb store

### PR DESCRIPTION
**Pull request by Teko012**
# Pull Request
## Problem
Some `fi`, `ee`, `lv` and `gb` stores were missing
## Solution
Add new stores, remove closed store

### CODE REVIEW

**Comment by Teko012** [comment]
@Ephigenia I'm sure there are some other stores missing. Maybe it could be auto generated from these: `https://www.ikea.com/fi/fi/meta-data/navigation/stores-detailed.json`

**Review by Ephigenia — APPROVED** [review]
I manually tested all the added stores and countries! Thanks for the contribution and extending the list of supported countries!

**Comment by Ephigenia** [comment]
> @Ephigenia I'm sure there are some other stores missing. Maybe it could be auto generated from these: https://www.ikea.com/fi/fi/meta-data/navigation/stores-detailed.json

Nice find! This even works for other countries and languages! Awesome I’ll add it!

**Comment by Ephigenia** [comment]
Added a project entry for this to not forget it if you might want to follow: https://github.com/Ephigenia/ikea-availability-checker/issues/156

**Comment by Teko012** [comment]
@Ephigenia Great! You could parse the available options from the `localizedSites` from here: `https://www.ikea.com/global/en/shared-data/regions.js` Most of it supports this, the rest (the list is fairly small) could be some kind of manual check/maybe a CI check where it calls the API and reports back if it finds a store or country not in the list maybe. That way we could extend it further easily if the API supports it (right now it just dies with a nodeJS error).

**Pull request merged**
